//! Solidity bindings generated by alloy's `sol!` macro.
//!
//! Only the functions gift-bot actually calls are declared — not the full
//! contract surface. This keeps the binding fast to compile and unambiguous
//! about what the bot depends on.

use alloy::sol;

sol! {
    #[sol(rpc)]
    #[allow(missing_docs)]
    contract GiftVault {
        /// Mirror of GiftVault.State in Solidity. Order is load-bearing —
        /// the enum is serialized as its ordinal (uint8) on the wire.
        #[derive(Debug, PartialEq, Eq)]
        enum State {
            Accumulating,
            Active,
            Burned,
        }

        /// Mirror of GiftVault.Platform in Solidity. Same ordinal ordering
        /// contract.
        #[derive(Debug, PartialEq, Eq)]
        enum Platform {
            GitHub,
            X,
        }

        /// Per-token record returned by `getGiftInfo`. Field order must stay
        /// in sync with `GiftInfo` in the contract — alloy decodes by
        /// position, not name.
        struct GiftInfo {
            State state;
            Platform platform;
            address receiver;
            uint256 balance;
            uint256 createdAt;
            string id;
        }

        /// Bind or rotate the claim receiver for `token`. Restricted — the
        /// bot EOA must have operator permission via `ProtocolManager`.
        function setReceiver(address token, address receiver) external;

        /// Returns the AccessManager (`ProtocolManager`) that decides which
        /// callers may invoke `restricted` functions. We use this to
        /// self-discover the ProtocolManager address at boot.
        function authority() external view returns (address);

        /// Read a token's gift metadata for validator pre-checks. The
        /// off-chain pipeline uses this to reject tweets whose tokens are
        /// unconfigured, already burned, or owned by a different handle —
        /// avoiding a guaranteed on-chain revert.
        function getGiftInfo(address token) external view returns (GiftInfo memory);

        /// Emitted by `setReceiver` on success. The executor parses tx
        /// receipts for this to confirm the write went through at the
        /// expected `(token, receiver)` pair.
        event ReceiverSet(address indexed token, address indexed receiver);
    }

    #[sol(rpc)]
    #[allow(missing_docs)]
    contract ProtocolManager {
        /// Permission query — returns (allowed, delay). `delay == 0` means
        /// the call is immediately allowed; otherwise the AccessManager
        /// mandates a scheduled call (not supported by this bot).
        function canCall(address caller, address target, bytes4 selector)
            external
            view
            returns (bool, uint32);
    }
}
